### ISSUE TITLE
Some suggested links

### ISSUE THREAD

**Issue by oskay** [beardicus/awesome-plotters#1]
I too collect plotter links. Here are some that might fit into your collection. Please feel free to incorporate all or none of these at your discretion. I've done a first-pass search for duplicates, but I may have missed some.  

(Disclosure: I'm with [Evil Mad Scientist](https://github.com/evil-mad)).

### Fonts
* [Single line font resources](http://imajeenyus.com/computer/20150110_single_line_fonts/index.shtml) by Lindsay Wilson

### Vector Creation
* [Penkit](https://github.com/paulgb/penkit) library by Paul Butler
* [generativeExamples](https://github.com/digitalcoleman/generativeExamples) by Christopher Coleman
* [Let's make map](http://svg-exporter.netlify.com) Mapzen SVG creator
* [SuperformulaSVG for web](https://jasonwebb.github.io/SuperformulaSVG-for-web/), a generative line art web app by Jason Webb
* [scribbleplot](https://github.com/bleeptrack/scribbleplot) by bleeptrack
* [penplot](https://github.com/mattdesl/penplot), a development environment for generative and algorithmic art by Matt DesLauriers
* [generativeBugs](https://github.com/bleeptrack/generativeBugs) Processing script for generating random bug images by bleeptrack

### Plotter Specific
* [RoboPaint](https://github.com/evil-mad/robopaint) software for WaterColorBot
* [AxiTurtle](https://github.com/ralphcrutzen/AxiTurtle) Turtle graphics for AxiDraw in Processing 

## Inspiration and Instruction
* [Surface Projection](https://bitaesthetics.com/posts/surface-projection.html) article by Paul Butler
* [Introduction to TSP art](https://wiki.evilmadscientist.com/TSP_art)
* [Hidden wireframe removal](https://trmm.net/Hidden_Wireframe) by Trammell Hudson

## Artists selling plotter-based artwork

* [Paul Rickards](http://biosrhythm.com/?page_id=1569)
* [Michael Fogleman ](https://www.michaelfogleman.com/plotter/)
* [inconvergent](http://buy.inconvergent.net/): Generative art by Anders Hoff
* [Customized street maps](https://www.literalstreetart.com/)
* [Monica Rizzolli](https://www.saatchiart.com/account/artworks/155196)
* [EmergentDesign ](https://emergentdesign.bigcartel.com/products)

**Comment by i-make-robots** [comment]
https://github.com/digitalcoleman/generativeExamples hover over the link and it actually points somewhere else.

**Comment by oskay** [comment]
@i-make-robots Updated. As long as I live, I will never get the hang of markdown.

**Comment by beardicus** [comment]
Thanks! I'll get these incorporated soon.

**Comment by beardicus** [comment]
All set... great links. Thanks again!
