### ISSUE TITLE
Motor Controllers addition

### ISSUE THREAD

**Issue by Kenno9000** [beardicus/awesome-plotters#18]
**EiBotBoard 
(EggBot Board)  Drives: AxiDraw, EggBot, WaterColorBot**
Integrates with Inkscape Extention
Current version 2.45 (c. 11-19)

**Available: 
EiBotBoard Schematics**   
https://www.schmalzhaus.com/EBB/  
(confirmed 3-12-19)

**EiBotBoard Board, Firmware, blog, manual, support:**    
(confirmed 3-12-19)
https://shop.evilmadscientist.com/productsmenu/188

**EiBotBoard Board (version 2.43, black**) 
(confirmed 3-12-19)
https://www.aliexpress.com/item/32789757886.html?spm=a2g0s.9042311.0.0.52d44c4drzRdC7

**Integration and software:**
EiBotBoard requires a serial interface, drivers and instructions are widely available, including evilmadscientist.com  or searching for USB to Serial Driver  CH340 or CH431  

**Eggbot - GitHub Pages**
(confirmed 3-12-19) 
https://evil-mad.github.io›EggBot›ebb
The Inkscape-based drivers for the EggBot, for the WaterColorBot, and for AxiDraw are written in python, and use this serial protocol.

**Grbl with Pen Servo / Laser Feature (Arduino UNO - ATMega328p version)**
(confirmed 3-12-19 but untested)
https://github.com/bdring/Grbl_Pen_Servo

**Comment by beardicus** [comment]
i added some of these links finally. thanks for the info!
