### ISSUE TITLE
Suggested links

### ISSUE THREAD

**Issue by i-make-robots** [beardicus/awesome-plotters#2]
the app with generative algorithms and image converters:
http://github.com/marginallyclever/makelangelo-software/

the hardware: http://www.makelangelo.com/

Disclosure: I make the Makelangelo.

**Comment by i-make-robots** [comment]
also
http://reddit.com/r/singleline
http://reddit.com/r/patternporn
http://www.reddit.com/r/PlotterArt

**Comment by i-make-robots** [comment]
https://www.hackster.io/michele1993/caravaggio-a-drawing-machine-76136b?ref=explore&ref_id=trending___&offset=3 caravaggio?

**Comment by beardicus** [comment]
Thanks for the links! Somebody else actually added the makelangelo-software in another PR this morning. Nice! I've also added the hardware link.

/r/plotterart was already on the list, and the other subreddits seem a little abandoned so I've not added those.

Thanks again, cheers!
