### ISSUE TITLE
Group chat

### ISSUE THREAD

**Issue by OzHawk** [beardicus/awesome-plotters#33]
Hey Beardicus,
I've recently embraced my inner plotterness and am looking for where the plotterphiles hang out online.
Your list is AWESOME, but it is missing links to current/active forums/social media hangouts where plotterphiles get together and share the the joy of plotters.
I've searched for FB groups, but didn't find any.
Do you know of any online plotter hangouts where I can ask questions?  So far my post have only been in general Retro Computing groups...and they are beginning to look at me funny. ;^)

**Comment by jimmykl** [comment]
Drawingbots Discord should fit the bill! https://discord.gg/agWsqHSm

**Comment by mhatalski** [comment]
There's a Discord Chat link as well as some other good resources on [drawingbots.net](https://drawingbots.net/)

**Comment by drewnoakes** [comment]
Thanks @mhatalski. Turns out my Discord problem was unrelated to the link above.

**Comment by beardicus** [comment]
👋🏻 thanks for the Q @OzHawk ... there's a link to the drawingbots discord in the "community" section already, along with a few other things. i'll leave this issue open for a bit in case we can catch any other links that i've missed, but i think that discord is probably the most relevant.

**Comment by OzHawk** [comment]
Sorry @beardicus, I replied after @jimmykl commented, but I realise now that it was just to him.
After Jimmy replied I went back and had a "Mothers Look" and sure enough, there was what I was looking for in the "Community" section.  I've since joined the Discord server and am very happy with the assistance that I've recieved.  Thanks for maintaining an AWESOME plotter list.
One of the areas of plotters that I have had difficulty finding information is regarding vintage plotter manuals.  I have been scanning and uploading new ones I find to Archive.org.

**Comment by beardicus** [comment]
@OzHawk please keep in touch re: newly uploaded plotter manuals! i do a periodic search of the archive but it's sometimes hard to tell what's new and what's already included in the "manuals" section here.

**Comment by OzHawk** [comment]
Will do.  I've only scanned one myself so far, and uploaded another one.  The important part is getting the tags and meta data correct.  I found the one I uploaded already on Archive.org later, but without correct tags and meta data it didn't come up in any of my searches.  I have a manual (and some brochures) for the Houston Instrument DMP-51 that I need to scan and upload.
