### ISSUE TITLE
UPDATE: Houston Instruments Documents on Archive.org

### ISSUE THREAD

**Issue by OzHawk** [beardicus/awesome-plotters#34]
I've uploaded some newly scanned documents on Archive.org, under the user name [OzHawk.](https://archive.org/details/@ozhawk)
The most useful of these documents is probably the [Houston Instrument DM/PL Command Language manual](https://archive.org/details/hi-dmpl-command-language/mode/2up).  I haven't come across this manual anywhere on the internet.
The final one I have to scan is the DMP-51 User manual.

**Comment by beardicus** [comment]
added a bunch of those... thanks!
