### ISSUE TITLE
New Manual: Houston Instruments HIPLOT DMP-51/52 Operation Manual

### ISSUE THREAD

**Issue by OzHawk** [beardicus/awesome-plotters#35]
Here's another Houston Instrument manual that doesn't exist anywhere else on the internet.  This one includes the assembly drawings, parts list, and schematic diagrams for the DMP-51/52.
https://archive.org/details/hi-dmp-51-52-operation-manual

**Comment by beardicus** [comment]
thanks for the upload and link!
