### ISSUE TITLE
plotter maps

### ISSUE THREAD

**Issue by renschler** [beardicus/awesome-plotters#8]
Under the "plotter art for sale section" there's a link to https://www.literalstreetart.com/.

As far as I can tell it's not actually plotter art, but just a custom printed map. Still cool though.

**Comment by beardicus** [comment]
Actually, I just looked and they _can_ do actual pen plotter output. You choose *pen plotter print* under the *size* heading in their map editor. Not terribly obvious but I think I'll leave it in and just update the description.

**Comment by renschler** [comment]
oh sweet! sorry my bad 🤦‍♂️
